spring.application.name=javakafka

spring.datasource.url=jdbc:postgresql://localhost:5432/javakafka_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.use_sql_comments=false

server.port=8080